export {
  EXERCISE_GRAMMAR_BLANK_CLASS as GRAMMAR_PASSAGE_BLANK_CLASS,
  EXERCISE_OPTION_EN_CLASS as GRAMMAR_OPTION_TEXT_CLASS,
  EXERCISE_PASSAGE_EN_CLASS as GRAMMAR_PASSAGE_TEXT_CLASS,
} from '../exercise/exercise-typography'
